services:
    mysql:
        image: 'mysql:5.7'
        container_name: 'ea_mysql'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './docker-data/mysql:/var/lib/mysql:rw'
        networks:
            - ea_net
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        container_name: 'ea_redis'
        networks:
            - ea_net
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    app:
        image: listados/escolhaazul:latest
        container_name: 'ea_prod'
        expose:
            - "9000"
        volumes:
            - './storage:/application/storage'
            - app-public:/application/public
            - ./.env:/application/.env:ro
        networks:
            - ea_net
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy

    nginx:
        image: 'nginx:alpine'
        container_name: 'ea_nginx'
        expose:
          - "80"
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
#            - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
#            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
        volumes:
            - './phpdocker/nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf'
            - app-public:/application/public
        networks:
            - ea_net
            - nginx-proxy_default
        depends_on:
            - app

networks:
    ea_net:
        driver: bridge
    nginx-proxy_default:
        external: true

volumes:
    app-public:
        driver: local
