version: '3.1'
services:
  redis_ea:
    image: 'redis:alpine'

  mysql_ea:
    image: 'mysql:5.7'
    working_dir: /application
    container_name: 'ea_mysql'
    volumes:
      - './docker-data/mysql:/var/lib/mysql:rw'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      #- MYSQL_USER=escolha
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    networks:
      - ea_net

  webserver_ea:
    image: 'nginx:alpine'
    container_name: 'web_ea'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - ea_net
      - nginx-proxy_default

  php-fpm-ea:
    build: phpdocker/php-fpm
    working_dir: /application
    container_name: phpea
    volumes:
      - '.:/application'
      - '.env:/application/.env'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    networks:
      - ea_net

networks:
  ea_net:
  nginx-proxy_default:
    external: true
