###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  redis:
    image: 'redis:alpine'

  mysql:
    image: 'mysql:5.7'
    working_dir: /application
    container_name: 'dbvistoria-vue'
    volumes:
      - './phpdocker/mysql/data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=livre
      - MYSQL_DATABASE=vistoria
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=livre
    ports:
      - '50001:3306'
    networks:
      - nginx-proxy_default

  webserver:
    image: 'nginx:alpine'
    container_name: 'webvistoria-vue'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '5050:80'
    environment:
      - VIRTUAL_HOST=vistorianomades.listados.com.br
      - LETSENCRYPT_HOST=vistorianomades.listados.com.br
      - LETSENCRYPT_EMAIL=franciscoanto@gmail.com
    networks:
      - nginx-proxy_default

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    container_name: phpvistoria
    volumes:
      - '.:/application'
      - '.env:/application/.env'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
    networks:
      - nginx-proxy_default

networks:
  nginx-proxy_default:
    external: true
