const immobile = [
    {
        immobiles_id: 399138,
        immobiles_cep: "60426110",
        immobiles_address: "Rua Matos Vasconcelos",
        immobiles_number: "1575",
        immobiles_complement: "",
        immobiles_district: "Damas",
        immobiles_city: "Fortaleza",
        immobiles_state: "CE",
        immobiles_reference_point: "",
        created_at: "2023-11-18 15:33:21",
        updated_at: "2023-11-18 15:33:21",
        immobiles_code: "CA0201",
        immobiles_status: "Ativo",
        immobiles_date_register: "2023-10-27 00:00:00",
        immobiles_date_update: "2023-11-17 00:00:00",
        immobiles_property_title: "Casa com 3 dormitórios para alugar, 73 m² por R$ 1.200 /mês - Damas - Fortaleza/CE",
        immobiles_publish: "1",
        immobiles_name_condo: "",
        immobiles_business_status: "Padrão",
        immobiles_type_offer: 1,
        immobiles_selling_price: "0",
        immobiles_type_rental: "3",
        immobiles_rental_price: 1200,
        immobiles_rental_warranty: "",
        immobiles_board_on_site: "1",
        immobiles_useful_area: "73",
        immobiles_total_area: "191",
        immobiles_metrica_unit: "M2",
        immobiles_property_default: "Regular",
        immobiles_property_localization: "Média",
        immobiles_ocupacion: "Desocupado",
        immobiles_accept_negotiation: "1",
        immobiles_face_immobile: "Nenhum",
        immobiles_qtd_dormitory: "3",
        immobiles_qtd_suite: "",
        immobiles_qtd_toilet: "1",
        immobiles_qtd_uncovered_jobs: "",
        immobiles_ps: "IMOVEL: casa, com sala, recuo frontal, 03 quartos, corredor,  01 banheiro, cozinha, área de serviço, quintal e vaga para moto"
            + "Água e energia individualizados. LOCALIZAÇÃO: Próximo a Av. José Bastos, Estação do Metrofor Couto Fernandes, Auto Shopping José Bastos e Cometa Supermercados.",
        immobiles_finality: "Residencial",
        immobiles_latitude: "-3.7571549415588380000000000",
        immobiles_longitude: "-38.5558586120605500000000000",
        immobiles_iptu_price: 22.07,
        immobiles_condominium_price: 0,
        immobiles_type_immobiles: "Casa",
        immobiles_type_publication: "3",
        immobiles_tour_virtual: "http://www.grautour.com/public/plugins/1705191495196031/ver-360.php?id=CA0201",
        immobiles_price_season: 0,
        immobiles_face: "Nenhum",
        immobiles_electronic_door: 0,
        immobiles_front_sea: 0,
        immobiles_sea_shore: 0,
        immobiles_wine_house: 0,
        immobiles_elevator: 0,
        immobiles_barbecue_grill: 0,
        immobiles_poll: 0,
        immobiles_sports_court: 0,
        immobiles_soccer_field: 0,
        immobiles_furnished: 0,
        immobiles_floors: 0
    },
    {
        immobiles_id: 399139,
        immobiles_cep: "60130061",
        immobiles_address: "Rua Marcondes Pereira",
        immobiles_number: "261",
        immobiles_complement: "",
        immobiles_district: "Joaquim Távora",
        immobiles_city: "Fortaleza",
        immobiles_state: "CE",
        immobiles_reference_point: "",
        created_at: "2023-11-18 15:33:21",
        updated_at: "2023-11-18 15:33:21",
        immobiles_code: "CA0200",
        immobiles_status: "Ativo",
        immobiles_date_register: "2023-10-20 00:00:00",
        immobiles_date_update: "2023-11-17 00:00:00",
        immobiles_property_title: "Casa com 7 dormitórios para alugar, 230 m² por R$ 4.000/mês - Joaquim Távora - Fortaleza/CE",
        immobiles_publish: "1",
        immobiles_name_condo: "",
        immobiles_business_status: "Padrão",
        immobiles_type_offer: 1,
        immobiles_selling_price: "0",
        immobiles_type_rental: "3",
        immobiles_rental_price: 4000,
        immobiles_rental_warranty: "",
        immobiles_board_on_site: "1",
        immobiles_useful_area: "230",
        immobiles_total_area: "338",
        immobiles_metrica_unit: "M2",
        immobiles_property_default: "Regular",
        immobiles_property_localization: "Ótima",
        immobiles_ocupacion: "Desocupado",
        immobiles_accept_negotiation: "",
        immobiles_face_immobile: "Nenhum",
        immobiles_qtd_dormitory: "7",
        immobiles_qtd_suite: "4",
        immobiles_qtd_toilet: "4",
        immobiles_qtd_uncovered_jobs: "2",
        immobiles_ps: "IMOVEL: Casa para fins comerciais ou residencial, com terraço, sala, 07 quartos ( sendo 04 suítes, 03 quartos social ). 01 suíte master com jardim de inverno, corredor, cozinha, área de serviço e dispensa. 02 vagas de garagem. TAXA DE LIXO: R$ 93,20 REF; 2023. ADICIONAL. Existe um espaço externo que está desativada, precisa de reforma.   LOCALIZAÇÃO: Marcondes Pereira nº 261 Joaquim Távora, PROX: Av. Barão de Studart e Av. Soriano Albuquerque, Colégio Antares - Sede Irmã Maria, Abaeté Boteco, EEFM Padre Rocha, Auto Escola Igor, Sportgym AcademiaAABB - Associação Atlética Banco do Brasil",
        immobiles_finality: "Residencial",
        immobiles_latitude: "-3.7464988231658936000000000",
        immobiles_longitude: "-38.5147361755371100000000000",
        immobiles_iptu_price: 282.35,
        immobiles_condominium_price: 0,
        immobiles_type_immobiles: "Casa",
        immobiles_type_publication: "3",
        immobiles_tour_virtual: "http://www.grautour.com/public/plugins/1705191495196031/ver-360.php?id=CA0200",
        immobiles_price_season: 0,
        immobiles_face: "Nenhum",
        immobiles_electronic_door: 0,
        immobiles_front_sea: 0,
        immobiles_sea_shore: 0,
        immobiles_wine_house: 0,
        immobiles_elevator: 0,
        immobiles_barbecue_grill: 0,
        immobiles_poll: 0,
        immobiles_sports_court: 0,
        immobiles_soccer_field: 0,
        immobiles_furnished: 0,
        immobiles_floors: 0
    },
    {
        immobiles_id: 399140,
        immobiles_cep: "60040630",
        immobiles_address: "Rua Doutor José Vítor",
        immobiles_number: "131",
        immobiles_complement: "Ap 202",
        immobiles_district: "Fátima",
        immobiles_city: "Fortaleza",
        immobiles_state: "CE",
        immobiles_reference_point: "",
        created_at: "2023-11-18 15:33:22",
        updated_at: "2023-11-18 15:33:22",
        immobiles_code: "AP0369",
        immobiles_status: "Ativo",
        immobiles_date_register: "2023-10-06 00:00:00",
        immobiles_date_update: "2023-11-17 00:00:00",
        immobiles_property_title: "REPASSE - Apartamento com 3 dormitórios à venda, 107 m² por R$ 129.000 - Fátima - Fortaleza/CE",
        immobiles_publish: "1",
        immobiles_name_condo: "Edifício Jacy",
        immobiles_business_status: "Padrão",
        immobiles_type_offer: 1,
        immobiles_selling_price: "129000.00",
        immobiles_type_rental: "",
        immobiles_rental_price: 0,
        immobiles_rental_warranty: "",
        immobiles_board_on_site: "1",
        immobiles_useful_area: "107",
        immobiles_total_area: "107",
        immobiles_metrica_unit: "M2",
        immobiles_property_default: "Não informado",
        immobiles_property_localization: "Ótima",
        immobiles_ocupacion: "Desocupado",
        immobiles_accept_negotiation: "1",
        immobiles_face_immobile: "Nenhum",
        immobiles_qtd_dormitory: "3",
        immobiles_qtd_suite: "1",
        immobiles_qtd_toilet: "3",
        immobiles_qtd_uncovered_jobs: "1",
        immobiles_ps: "IMOVEL: Apartamento no 2º andar com ampla sala, 03 quartos sendo 01 suíte, 3 banheiros, cozinha, dependência de empregada e lavanderia."
            + "CONDOMINIO: 01 vaga de garagem, água incluso, zelador e vigia."
            + "LOCALIZAÇÃO: Prox. a Av. Aguanambi, Pão de Açúcar, Apoema Curso Técnico e Unicursos Fortaleza."
            + "O apartamento está atualmente passando por um processo de regularização de documentação, proporcionando a oportunidade perfeita para um comprador/investidor perspicaz adquirir um imóvel abaixo do preço de mercado. "
            + "O imóvel necessita de reformas/reparos, conforme visto nas fotos.",
        immobiles_finality: "Residencial",
        immobiles_latitude: "-3.7477269172668457000000000",
        immobiles_longitude: "-38.5241165161132800000000000",
        immobiles_iptu_price: 601.75,
        immobiles_condominium_price: 462,
        immobiles_type_immobiles: "Apartamento",
        immobiles_type_publication: "2",
        immobiles_tour_virtual: "",
        immobiles_price_season: 0,
        immobiles_face: "Nenhum",
        immobiles_electronic_door: 0,
        immobiles_front_sea: 0,
        immobiles_sea_shore: 0,
        immobiles_wine_house: 0,
        immobiles_elevator: 3,
        immobiles_barbecue_grill: 0,
        immobiles_poll: 0,
        immobiles_sports_court: 0,
        immobiles_soccer_field: 0,
        immobiles_furnished: 0,
        immobiles_floors: 2
    }
]

export default immobile