name: escolhaazul-actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-js-css:
    name: Build JS CSS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.PUSH_TOKEN }}
        
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - run: npm install