name: escolhaazul-actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-js-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: '159.223.144.245'
          key: ${{ secrets.SSH_PASSWORD }}
          script: cd /home/dev/escolhaazul && sh deploy.sh
