name: escolhaazul-actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-js-css:
    name: Build JS CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      
      - name: Set Up Node
        run: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: npm install