name: escolhaazul-actions

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master"]

jobs:
  build-js-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Build the stack
        run: docker-compose up -d
        
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build